package io.threatrix.typing;

public enum LanguageType {

    JAVASCRIPT (true),  // DONE
    PYTHON (true, ScanLookupType.SHA256),
    JAVA (true),        // DONE
    TYPESCRIPT(true),   // DONE
    CSHARP (true),      // DONE
    PHP (true),         // DONE
    CPP (true),         // DONE
    SHELL (true),       // DONE
    C (true),           // DONE
    RUBY (true),        // DONE
    GO (true),          // DONE
    GROOVY (true),      // DONE
    KOTLIN (true),      // DONE
    OBJECTIVE_C (true),
    PERL (true),
    PERL6 (true),
    PLPGSQL (true),
    R (true),
    RUST (true),
    SCALA (true),
    SWIFT (true),


    ONE_C_ENTERPRISE,
    ABAP,
    ACTIONSCRIPT,
    ADA,
    AGDA,
    AGS_SCRIPT,
    ALLOY,
    AMPL,
    ANTLR,
    APEX,
    APL,
    APPLESCRIPT,
    ARC,
    ARDUINO,
    ASP,
    ASPECTJ,
    ASSEMBLY,
    ATS,
    AUGEAS,
    AUTOHOTKEY,
    AUTOIT,
    AWK,
    BATCHFILE,
    BEFUNGE,
    BISON,
    BITBAKE,
    BLITZBASIC,
    BLITZMAX,
    BLUESPEC,
    BOO,
    BRAINFUCK,
    BRIGHTSCRIPT,
    BRO,
    C2HS_HASKELL,
    CAP_N_PROTO,
    CARTOCSS,
    CEYLON,
    CHAPEL,
    CHARITY,
    CHUCK,
    CIRRU,
    CLARION,
    CLEAN,
    CLICK,
    CLIPS,
    CLOJURE,
    COBOL,
    COFFEESCRIPT,
    COLDFUSION_CFC,
    COLDFUSION,
    COMMON_LISP,
    COMPONENT_PASCAL,
    COOL,
    COQ,
    CRYSTAL,
    CSOUND_DOCUMENT,
    CSOUND_SCORE,
    CSOUND,
    CUDA,
    CYCRIPT,
    CYTHON,
    D,
    DART,
    DIGITAL_COMMAND_LANGUAGE,
    DM,
    DOGESCRIPT,
    DTRACE,
    DYLAN,
    E,
    EC,
    ECL,
    ECLIPSE,
    EIFFEL,
    ELIXIR,
    ELM,
    EMACS_LISP,
    EMBERSCRIPT,
    EQ,
    ERLANG,
    FACTOR,
    FANCY,
    FANTOM,
    FILEBENCH_WML,
    FILTERSCRIPT,
    FLUX,
    FORTH,
    FORTRAN,
    FREEMARKER,
    FREGE,
    FSHARP,
    GAME_MAKER_LANGUAGE,
    GAMS,
    GAP,
    GCC_MACHINE_DESCRIPTION,
    GDB,
    GDSCRIPT,
    GENIE,
    GENSHI,
    GHERKIN,
    GLSL,
    GLYPH,
    GNUPLOT,
    GOLO,
    GOSU,
    GRACE,
    GRAMMATICAL_FRAMEWORK,
    GROOVY_SERVER_PAGES,
    HACK,
    HARBOUR,
    HASKELL,
    HAXE,
    HCL,
    HLSL,
    HTML,
    HY,
    HYPHY,
    IDL,
    IDRIS,
    IGOR_PRO,
    INFORM_7,
    INNO_SETUP,
    IO,
    IOKE,
    ISABELLE,
    J,
    JASMIN,
    JAVA_SERVER_PAGES,
    JFLEX,
    JISON_LEX,
    JISON,
    JSONIQ,
    JSX,
    JULIA,
    KICAD,
    KRL,
    LABVIEW,
    LASSO,
    LEAN,
    LEX,
    LFE,
    LILYPOND,
    LIMBO,
    LITERATE_AGDA,
    LITERATE_COFFEESCRIPT,
    LITERATE_HASKELL,
    LIVESCRIPT,
    LLVM,
    LOGOS,
    LOGTALK,
    LOLCODE,
    LOOKML,
    LOOMSCRIPT,
    LSL,
    LUA,
    M,
    M4,
    M4SUGAR,
    MAKEFILE,
    MAKO,
    MARKDOWN,
    MATHEMATICA,
    MATLAB,
    MAX,
    MAXSCRIPT,
    MERCURY,
    METAL,
    MINID,
    MIRAH,
    MODELICA,
    MODULA_2,
    MODULE_MANAGEMENT_SYSTEM,
    MONKEY,
    MOOCODE,
    MOONSCRIPT,
    MQL4,
    MQL5,
    MUF,
    MUPAD,
    MYGHTY,
    NCL,
    NEMERLE,
    NESC,
    NETLINX,
    NETLINX_ERB,
    NETLOGO,
    NEWLISP,
    NIM,
    NIT,
    NIX,
    NSIS,
    NU,
    NUMPY,
    OBJECTIVE_CPP,
    OBJECTIVE_J,
    OCAML,
    OMGROFL,
    OOC,
    OPA,
    OPAL,
    OPENCL,
    OPENEDGE_ABL,
    OPENSCAD,
    OX,
    OXYGENE,
    OZ,
    P4,
    PAN,
    PAPYRUS,
    PARROT_ASSEMBLY,
    PARROT_INTERNAL_REPRESENTATION,
    PARROT,
    PASCAL,
    PAWN,
    PICOLISP,
    PIGLATIN,
    PIKE,
    PLSQL,
    POGOSCRIPT,
    PONY,
    POV_RAY_SDL,
    POWERBUILDER,
    POWERSHELL,
    PROCESSING,
    PROLOG,
    PROPELLER_SPIN,
    PURE_DATA,
    PUREBASIC,
    PURESCRIPT,
    QMAKE,
    QML,
    RACKET,
    RAGEL,
    RASCAL,
    REALBASIC,
    REASON,
    REBOL,
    RED,
    REDCODE,
    REN_PY,
    RENDERSCRIPT,
    REXX,
    ROUGE,
    SAGE,
    SALTSTACK,
    SAS,
    SCHEME,
    SCILAB,
    SELF,
    SHELLSESSION,
    SHEN,
    SLASH,
    SMALI,
    SMALLTALK,
    SMARTY,
    SMT,
    SOURCEPAWN,
    SQF,
    SQLPL,
    SQUIRREL,
    STAN,
    STANDARD_ML,
    STATA,
    SUPERCOLLIDER,
    SYSTEMVERILOG,
    TCL,
    TERRA,
    THRIFT,
    TI_PROGRAM,
    TLA,
    TURING,
    TXL,
    UNIFIED_PARALLEL_C,
    UNKNOWN,
    UNO,
    UNREALSCRIPT,
    URWEB,
    VALA,
    VCL,
    VERILOG,
    VHDL,
    VIM_SCRIPT,
    VISUAL_BASIC,
    VOLT,
    WEBIDL,
    WISP,
    X10,
    XBASE,
    XC,
    XOJO,
    XPAGES,
    XPROC,
    XQUERY,
    XS,
    XSLT,
    XTEND,
    YACC,
    ZEPHIR,
    ZIMPL;

    private boolean common = false;

    private ScanLookupType lookupType = ScanLookupType.SHA1;

    LanguageType(boolean common) {}

    LanguageType(boolean common, ScanLookupType lookupType) {
        this.common = common;
        this.lookupType = lookupType;
    }

    LanguageType() {}

    public ScanLookupType getLookupType() {
        return lookupType;
    }
}
